#!/bin/bash

# Copyright 2019 Tom Peters
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

files=$(
	git ls-files --cached --others --exclude-standard -- '*.js' '*.css' '*.vue' \
		| xargs grep -L 'GNU Affero General Public License'
	)

if [[ -n $files ]]; then
	echo "The following files are missing a license:" >&2
	echo "$files" >&2
	echo "Please run hack/apply-license.pl" >&2
	exit 1
fi
