name: Build
on:
  push:
    branches: [master]
env:
  IMAGE: docker.pkg.github.com/sqmgr/sqmgr-vue/sqmgr-vue
jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch origin +refs/tags/*:refs/tags/*
      - name: set version
        run: echo "::set-env name=VERSION::$(git describe --always --dirty)"
      - name: docker log in
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: docker-build
        run: |
          docker build --build-arg version=${{ env.VERSION }} -t ${{ env.IMAGE }}:${{ env.VERSION }} .
          docker tag ${{ env.IMAGE }}:${{ env.VERSION }} ${{ env.IMAGE }}:latest
      - name: docker-push
        run: |
          docker push ${{ env.IMAGE }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE }}:latest
