name: Build

on:
  push:
    branches: [master]

env:
  IMAGE: ${{ github.repository }}
  REGISTRY: ghcr.io

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest

    permissions:
        contents: read
        packages: write
        attestations: write
        id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: set version
        run: echo "VERSION=$(git describe --always)" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker-build
        run: |
          docker build --build-arg version=${{ env.VERSION }} -t ${{ env.IMAGE }}:${{ env.VERSION }} .
          docker tag ${{ env.IMAGE }}:${{ env.VERSION }} ${{ env.IMAGE }}:latest
      - name: docker-push
        run: |
          docker push ${{ env.IMAGE }}:${{ env.VERSION }}
          docker push ${{ env.IMAGE }}:latest

      - name: k8s-deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deploy sqmgr-vue nginx=${{ env.IMAGE }}:${{ env.VERSION }} --record

      - name: k8s-rollout
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deploy sqmgr-vue