name: Deploy
on: [deployment]
env:
  IMAGE: docker.pkg.github.com/sqmgr/sqmgr-vue/sqmgr-vue
jobs:
  deploy:
    name: 'Deploy to Production'
    runs-on: ubuntu-latest
    steps:
      - name: 'deployment pending'
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'pending'
          token: '${{ github.token }}'

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: git fetch origin +refs/tags/*:refs/tags/*

      - name: set image name
        run: echo "::set-env name=IMAGE_TAG::$IMAGE:$(git describe --always --dirty)"

      - name: docker log in
        run:  echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: k8s-deploy
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deploy sqmgr-vue nginx=${{ env.IMAGE_TAG }} --record

      - name: k8s-rollout
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: rollout status deploy sqmgr-vue

      - name: 'deployment success'
        if: success()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'success'
          token: '${{ github.token }}'

      - name: 'deployment failure'
        if: failure()
        uses: 'deliverybot/deployment-status@master'
        with:
          state: 'failure'
          token: '${{ github.token }}'

